name: Quick APK Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Finder-Tracker-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Success Message
      run: |
        echo "🎉 APK built successfully!"
        echo "📱 File: app-debug.apk"
        echo "📦 Download from Actions tab"
        echo "⏱️ Build completed in ${{ steps.build.outputs.duration }}" 